sudo: required 

dist: trusty

language: cpp

notifications:
  email: on_failure

branches:
  only:
    - master
    - stable 
    - coverity_scan

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KtzmdEmAEnA5BCiYFMMX1Y/4ZGgwOofYRM2/xPeVK7nHyiVfevYo1Dd0vbP+xZWvHdI1pGg0592VyfEb31x49oilMozIyAWUcNGnMhAu/XwcuwWjyyLjvS5PpAYGMTfObiJcuavbH6kwy8Pnz/3ovtVWeIawDNSvw16EJ0qtbIHQLRjjwCk77dsQTaR27dYr8W5DtYsJK6zX8Bu6AW7FXV3u5jhi/e9C8th1Em5YjseUP66hbJ5jSIArhUi1wojQAoOnr2rYYgmIjjtKZSPu/yIxdAt8BV5UxJim6YeTVWlu2uJV6L53n9n+gwDxteARE+4NM3BARBv4VpNx8eSKNbDPyxLb15mgrPjeF8Yyi9o8ROzmhQDRK415FLYTULHslOYSZQsL+of982G6krDyaZCWx6ahQXlt6f6/TfQQ7M6nLmPXes2HTue+OMG4aiIxQyQ4hNMPZPb56wNWLIwhth6TkZ5KpotgiRYkaV8xUbRsZNcRFImlJIkmFSH3OyhcBu9kNk1S5i/60La+XlF+Avw8sqj7jLjhF31NKLVpHU3ofCw6h6E9cwToN0QoxM8QAaumqdlnq7MhjiSeqO5Q+9GJi8tq966T1lLW1mGAKE51ecyXL5F91v5T7gzOWSibaVEIwUBAcOvkCw7BdNliI/XvUW7nD/SjSPQpD8xWErk="

##before_install:
##  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "amete/hello_world"
      description: "Testbed for Travis-CI thingzzz :)"
    notification_email: serhanmete@gmail.com
    build_command_prepend: "mkdir -p build; cd build; $(type -p cmake) -DCMAKE_CXX_COMPILER=$(type -p g++) -DCMAKE_C_COMPILER=$(type -p gcc) .."
    build_command: "make -j"
    branch_pattern: coverity_scan

script:
  - .travis-scripts/build-test.sh
