sudo: required

# Test across multiple containers 
env:
  - DIMAGE=graemeastewart/u16-dev
  - DIMAGE=graemeastewart/c7-dev

services:
  - docker
  
before_install:
  - docker pull $DIMAGE
 
install:
  - /bin/true

# Light customisation of build for different container images
script:
  - if [ "$DIMAGE" = graemeastewart/u16-dev ]; then docker run -e CXX=g++-7 -e CC=gcc-7 -v $(pwd):/mnt $DIMAGE /mnt/.travis-scripts/build-test.sh; fi
  - if [ "$DIMAGE" = graemeastewart/c7-dev ]; then docker run -e CMAKE=cmake3 -v $(pwd):/mnt $DIMAGE scl enable devtoolset-7 /mnt/.travis-scripts/build-test.sh; fi
