name: Clang-Format

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #- uses: amete/clang-format-action@v0.1

    - name: Add a dummy text, commit and push
      run: |
        git config --global user.email "clang-format@github-actions"
        git config --global user.name "clang-format"
        echo "////SERHAN" >> $GITHUB_WORKSPACE/src/hello_world.cxx
        git commit -a -m "Apply clang-format" || true
        git push -u origin ${GITHUB_REF#*refs/heads/}
